services:
  sunat-worker:
    build: .
    container_name: sunat_worker
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    # Si tu SQL Server está en la red del host y necesitas DNS/hosts específicos, puedes añadir:
    # extra_hosts:
    #   - "sqlserver.local:192.168.10.202"
